on:
  push:
  pull_request:


jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: frontend/.nvmrc
          cache: yarn
          cache-dependency-path: yarn.lock
      - run: yarn install
      - run: yarn workspaces run lint:ci
